# methods/order.http

POST http://localhost:3000/orders
Content-Type: application/json

{
  "userId": "476e40ca-9b81-44ef-b643-da8d05010d87",
  "products": [
    {
      "id": "edf75a6e-6f47-461c-aa80-a8b1104be8b8"
    },
    {
      "id": "c1c41e5d-e563-494a-89bc-3935f6f6bd6e"
    }
  ]
}

###
GET http://localhost:3000/orders

###
GET http://localhost:3000/orders/ac4619e9-d3ec-4f04-a7c1-59438e5b3dba