# Definir variables locales
@base_url = http://localhost:3000/
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyNzM4MGJlOS0xMmRhLTRkYWMtODhiOC0zNmFkZTVhZGQxZTAiLCJpZCI6IjI3MzgwYmU5LTEyZGEtNGRhYy04OGI4LTM2YWRlNWFkZDFlMCIsImVtYWlsIjoidXNlcjFAZ21haWwuY29tIiwicm9sZXMiOlsiYWRtaW4iXSwiaWF0IjoxNzIxNzk2Njc2LCJleHAiOjE3MjI2NjA2NzZ9.fAz381sJ44eh3-TdaFTwHcW0i1Qs0nWOfJpcY8yVBV4
@user_id = 4ca18e77-f30c-4702-a90a-0e8cae90b6d1

# ========== Auth ==========
### signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "name": "New User 2",
  "password": "P4ss123@",
  "address": "new address",
  "phone": "987654321",
  "country": "New Country",
  "city": "New City"
}

### signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "password": "P4ss123@"
}



# ==================== USERS ====================

### Get all users (with pagination) - Requires Authorization
GET http://localhost:3000/users
Authorization: Bearer {{token}}


### Get all users (with pagination) - Requires Authorization
GET http://localhost:3000/users?page=1&limit=1
Authorization: Bearer {{token}}

### Get a specific user by ID - Requires Authorization
GET http://localhost:3000/users/{{user_id}}
Authorization: Bearer {{token}}

### Update a user by ID - Requires Authorization
PUT http://localhost:3000/users/{{user_id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Updated User",
  "address": "updated address",
  "phone": "123456789",
  "country": "Updated Country",
  "city": "Updated City"
}

### Delete a user by ID - Requires Authorization
DELETE http://localhost:3000/users/{{user_id}}
Authorization: Bearer {{token}}

