# Definir variables locales
@base_url = http://localhost:3000/
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZTZmMThjZC1kODA1LTQ3ZGYtOWZhNy1lYTljNjFjMGNkOWQiLCJpZCI6IjllNmYxOGNkLWQ4MDUtNDdkZi05ZmE3LWVhOWM2MWMwY2Q5ZCIsImVtYWlsIjoidXNlcjFAZ21haWwuY29tIiwicm9sZXMiOlsiYWRtaW4iXSwiaWF0IjoxNzI0MzQ2NDI5LCJleHAiOjE3MjUyMTA0Mjl9.frmNGRB0DR-aXldkQCZ2sX4mwF-kjjEsIHeXPvJAO84
@user_id = 4ca18e77-f30c-4702-a90a-0e8cae90b6d1

# ========== Auth ==========
### signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "User1235@gmail.com",
  "name": "New User 2",
  "password": "P4ss123@",
  "address": "new address",
  "phone": "987654321",
  "country": "New Country",
  "city": "New City",
  "whatsapp": "123123123",
  "roles": ["admin"]
}

### signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "User1@gmail.com",
  "password": "P4ss123@"
}



# ==================== USERS ====================

### Get all users (with pagination) - Requires Authorization
GET http://localhost:3000/users
Authorization: Bearer {{token}}


### Get all users (with pagination) - Requires Authorization
GET http://localhost:3000/users?page=1&limit=2
Authorization: Bearer {{token}}

### Get a specific user by ID - Requires Authorization
GET http://localhost:3000/users/{{user_id}}
Authorization: Bearer {{token}}

### Update a user by ID - Requires Authorization
PUT http://localhost:3000/users/{{user_id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Updated User",
  "address": "updated address",
  "phone": "123456789",
  "country": "Updated Country",
  "city": "Updated City"
}

### Delete a user by ID - Requires Authorization
DELETE http://localhost:3000/users/{{user_id}}
Authorization: Bearer {{token}}

