# methods/order.http

POST http://localhost:3000/orders
Content-Type: application/json

{
  "userId": "273920c5-1af7-4971-bfde-cb59e93cfc88",
  "products": [
    {
      "id": "59205335-2a96-4a02-947e-1154180fde33"
    },
    {
      "id": "8be9cac5-ce38-4cf0-b0aa-ad7be71e9134"
    }
  ]
}

###
GET http://localhost:3000/orders

###
GET http://localhost:3000/orders/cf83d8df-36ea-4f8f-bb60-c5b474735d43