POST http://localhost:3000/orders
Content-Type: application/json

{
  "userId": "8938b346-43ab-4350-a039-4c9e26f706a0",

  "products": [
    {
      "id": "6bacf924-1f33-4066-9cec-562cf33442c2"
    },

    {
      "id": "8e9d8226-ca6f-423b-8116-8c41df7a2f69"
    }
  ]
}

###
GET http://localhost:3000/orders